sudo: required
dist: trusty

language:
  - node_js
  - "6"

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database dms;' -U andeladeveloper

script:
  - npm test

after_success:
- npm run coveralls