sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - postgresql

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  -  npm --prefix ./client install ./client
  - psql -c 'create database travis;' -U postgres
  - dropdb --if-exists travis && createdb travis
  - NODE_ENV=test npm run migrate:test
  - npm run coveralls
after_success:
- npm run coveralls

after_failure:
- npm run coveralls