export const InitialState = {
  error: '',
  query: '',
  CreateUser: false,
  UserError: '',
  shouldRedirect: false,
  userInfo: {},
  users: {},
  usersCount: 0,
  adminUser: false,
  selectedUserData: {},
  displayFeedBack: 'none',
  AppInfo: 'Error occured while proccesing',
  AppInfoColor: '#D90707',
  editPreLoader: true,
  editFormState: true,
  success: false,
  docs: [],
  docCount: 0,
  publicDocs: {
    doc: [],
  },
  viewDoc: {
    title: '',
    content: '',
    access: '',
    creator: '',
  },
  docSuccess: false,
  editUserData: {
    firstname: '',
    lastname: '',
  },
  displayLoader: 'hide-element',
  docEdit: {
    title: '',
    content: '',
    access: [],
  },
  Deleted: false,
  deleteDoc: {
    title: '',
    content: '',
    access: [],
  },
  deleteUser: {
    username: '',
    id: 0,
  },
  editSuccess: false,
  search: [],
  lazyLoading: false,
  redirect: false,
  roles: [],
  refreshed: true,
  updateSearch: false,
};
